[package]
name = "bitpiece_svd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
parse_int = "0.9.0"
quick-xml = { version = "0.39.0", features = ["overlapped-lists", "serialize"] }
serde = { version = "1.0.228", features = ["derive"] }
